### ISSUE TITLE
make controller & view to revoke clients access.

### ISSUE THREAD

**Issue by hannesvdvreken** [iRail/PlugID#11]

**Comment by hannesvdvreken** [comment]
Only controllers & views, the models are implemented

**Comment by KoenDG** [comment]
Pushed controller & view. Functionality can be checked once auth_ tables get populated.

**Comment by hannesvdvreken** [comment]
you can populate auth_tables already.
/register to create new client (client for our application) != user
/oauth/authorize?redirect_uri=REDIRECT_URI&client_id=CLIENT_ID&response_type=code
then, you get a redirect to your redirect_uri?code=OUR_CODE
/oauth/access_token POST
    ?client_id=YOUR_CLIENT_ID
    &client_secret=YOUR_CLIENT_SECRET
    &grant_type=authorization_code
    &redirect_uri=YOUR_REGISTERED_REDIRECT_URI
    &code=CODE

returns your access_token, which is populated in the auth_tokens table
