### ISSUE TITLE
make oauth1 client with some equal functions to oauth2 client

### ISSUE THREAD

**Issue by hannesvdvreken** [iRail/PlugID#4]

**Comment by pietercolpaert** [comment]
If you make issues, please add a better description. We're working on an open-source platform. If an external person would like to contribute he will give up here.

**Comment by LennartMart** [comment]
There is a first version pushed of the oauth1_client. It's an implementation of the OAuth class provided by PHP. First attempt to implement this client can be found in Service(Service_twitter). All the functions aren't tested yet, so that has to be done first (smash those bugs!)

**Comment by jenssegers** [comment]
Make both the same structure as: http://php.net/manual/en/book.oauth.php

However, I don't really like CamelCase :(    _LIKE_ ←(Hannes)
